from act_detail_cfg import *
from act_fasten_cfg import *
from act_online_awards_cfg import *
from activity_cfg import *
from activity_gamble_cfg import *
from arena_awards_cfg import *
from arena_daily_awards_cfg import *
from arena_formation_cfg import *
from arena_mail_award_cfg import *
from arena_robot_mech_cfg import *
from charge_cfg import *
from equip_attr_cfg import *
from equip_cfg import *
from equip_intensify_cfg import *
from equip_upgrade_cfg import *
from equip_weak_cfg import *
from favor_cfg import *
from favor_level_cfg import *
from favor_marry_cfg import *
from favor_title_cfg import *
from fight_coeff_cfg import *
from gift_key_config import *
from group_cfg import *
from group_donate_cfg import *
from group_game_bird_awards_cfg import *
from group_game_tiger_awards_cfg import *
from group_game_tiger_cfg import *
from group_tra_cfg import *
from guide_main_cfg import *
from hero_base_cfg import *
from hero_exp_level_cfg import *
from hero_fate_cfg import *
from hero_pick_cfg import *
from hero_pick_rand_cfg import *
from hero_rand_attr_cfg import *
from hero_synt_cfg import *
from hero_upgrade_cfg import *
from hero_weak_cfg import *
from item_cfg import *
from item_exchange_cfg import *
from item_pack_cfg import *
from mall_pick_cfg import *
from mall_pick_rand_cfg import *
from mall_refresh_cfg import *
from mall_shop_cfg import *
from mall_tmp_cfg import *
from mission_act_awards_cfg import *
from mission_act_base_cfg import *
from mission_act_main_cfg import *
from mission_act_star_award_cfg import *
from mission_base_cfg import *
from mission_main_cfg import *
from mission_monster_cfg import *
from robot_name_cfg import *
from sensitive_char_cfg import *
from sign_award_cfg import *
from sign_cfg import *
from skill_cfg import *
from skill_effect_cfg import *
from skill_intensify_cfg import *
from spirit_cfg import *
from spirit_exp_level_cfg import *
from talent_base_cfg import *
from talent_detail_cfg import *
from task_daily_cfg import *
from task_main_cfg import *
from trial_awards_cfg import *
from trial_buff_cfg import *
from trial_cfg import *
from trial_fighter_rule_cfg import *
from trial_mail_award_cfg import *
from user_buy_gold_crit_cfg import *
from user_buy_refresh_cfg import *
from user_default_name_cfg import *
from user_func_cfg import *
from user_level_energy_cfg import *
from user_name_cfg import *
from vip_priv_cfg import *
from warship_cfg import *
from warship_intensify_cfg import *
from warship_upgrade_cfg import *
from warship_weak_cfg import *
