#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Date :
# @Author : Jiank
# @doc
#     !!! 前方配置高能, 均为自动生成, 随意改动可能会有不可思议的事情发生 !!!
# @end
# @copyright (C) 2015, kimech

item_cfg = {

    120000:{
        "No.": 120000,
        "type": 1,
        "quality": 0,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 100,
        "items": 0,
        "buy_price": 1,
        "effect_value": 100,
        "spirit_exp": 1,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120001:{
        "No.": 120001,
        "type": 1,
        "quality": 1,
        "need_level": 10,
        "can_sale": 1,
        "sale_price": 500,
        "items": 0,
        "buy_price": 2,
        "effect_value": 300,
        "spirit_exp": 3,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120002:{
        "No.": 120002,
        "type": 1,
        "quality": 2,
        "need_level": 20,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 3,
        "effect_value": 1000,
        "spirit_exp": 10,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120003:{
        "No.": 120003,
        "type": 1,
        "quality": 3,
        "need_level": 30,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 6,
        "effect_value": 3000,
        "spirit_exp": 30,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120004:{
        "No.": 120004,
        "type": 1,
        "quality": 4,
        "need_level": 40,
        "can_sale": 1,
        "sale_price": 10000,
        "items": 0,
        "buy_price": 12,
        "effect_value": 10000,
        "spirit_exp": 100,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120005:{
        "No.": 120005,
        "type": 1,
        "quality": 5,
        "need_level": 50,
        "can_sale": 1,
        "sale_price": 50000,
        "items": 0,
        "buy_price": 24,
        "effect_value": 30000,
        "spirit_exp": 500,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120010:{
        "No.": 120010,
        "type": 2,
        "quality": 0,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 100,
        "items": 0,
        "buy_price": 1,
        "effect_value": 10,
        "spirit_exp": 1,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120011:{
        "No.": 120011,
        "type": 2,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 500,
        "items": 0,
        "buy_price": 3,
        "effect_value": 30,
        "spirit_exp": 3,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120012:{
        "No.": 120012,
        "type": 2,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 15,
        "effect_value": 150,
        "spirit_exp": 15,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120013:{
        "No.": 120013,
        "type": 2,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 50,
        "effect_value": 500,
        "spirit_exp": 50,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120014:{
        "No.": 120014,
        "type": 2,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 10000,
        "items": 0,
        "buy_price": 150,
        "effect_value": 1500,
        "spirit_exp": 150,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120015:{
        "No.": 120015,
        "type": 2,
        "quality": 5,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 50000,
        "items": 0,
        "buy_price": 500,
        "effect_value": 5000,
        "spirit_exp": 500,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120020:{
        "No.": 120020,
        "type": 3,
        "quality": 0,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 100,
        "items": 0,
        "buy_price": 1,
        "effect_value": 10,
        "spirit_exp": 1,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120021:{
        "No.": 120021,
        "type": 3,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 500,
        "items": 0,
        "buy_price": 3,
        "effect_value": 30,
        "spirit_exp": 3,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120022:{
        "No.": 120022,
        "type": 3,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 15,
        "effect_value": 150,
        "spirit_exp": 15,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120023:{
        "No.": 120023,
        "type": 3,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 50,
        "effect_value": 500,
        "spirit_exp": 50,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120024:{
        "No.": 120024,
        "type": 3,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 10000,
        "items": 0,
        "buy_price": 150,
        "effect_value": 1500,
        "spirit_exp": 150,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120025:{
        "No.": 120025,
        "type": 3,
        "quality": 5,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 50000,
        "items": 0,
        "buy_price": 500,
        "effect_value": 5000,
        "spirit_exp": 500,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120030:{
        "No.": 120030,
        "type": 6,
        "quality": 1,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200000,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120031:{
        "No.": 120031,
        "type": 6,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200001,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120040:{
        "No.": 120040,
        "type": 10,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 100,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120041:{
        "No.": 120041,
        "type": 10,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120042:{
        "No.": 120042,
        "type": 10,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 10000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120043:{
        "No.": 120043,
        "type": 10,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 100000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120050:{
        "No.": 120050,
        "type": 6,
        "quality": 1,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200002,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120051:{
        "No.": 120051,
        "type": 6,
        "quality": 2,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200003,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120052:{
        "No.": 120052,
        "type": 6,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200004,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120060:{
        "No.": 120060,
        "type": 7,
        "quality": 1,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200005,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120061:{
        "No.": 120061,
        "type": 7,
        "quality": 2,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200006,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120062:{
        "No.": 120062,
        "type": 7,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200007,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120063:{
        "No.": 120063,
        "type": 7,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200008,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120064:{
        "No.": 120064,
        "type": 7,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200009,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120065:{
        "No.": 120065,
        "type": 7,
        "quality": 1,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200010,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120066:{
        "No.": 120066,
        "type": 7,
        "quality": 2,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200011,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120067:{
        "No.": 120067,
        "type": 7,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200012,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120068:{
        "No.": 120068,
        "type": 7,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200019,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120069:{
        "No.": 120069,
        "type": 7,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200026,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120070:{
        "No.": 120070,
        "type": 7,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200033,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120071:{
        "No.": 120071,
        "type": 7,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200040,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120072:{
        "No.": 120072,
        "type": 7,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200047,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120073:{
        "No.": 120073,
        "type": 7,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200054,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120074:{
        "No.": 120074,
        "type": 7,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 200061,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120100:{
        "No.": 120100,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100001,
        "broadcast": 0,
    },

    120101:{
        "No.": 120101,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100002,
        "broadcast": 0,
    },

    120102:{
        "No.": 120102,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100003,
        "broadcast": 0,
    },

    120103:{
        "No.": 120103,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100004,
        "broadcast": 0,
    },

    120104:{
        "No.": 120104,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100005,
        "broadcast": 0,
    },

    120105:{
        "No.": 120105,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100006,
        "broadcast": 0,
    },

    120106:{
        "No.": 120106,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100007,
        "broadcast": 0,
    },

    120107:{
        "No.": 120107,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100008,
        "broadcast": 0,
    },

    120108:{
        "No.": 120108,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100009,
        "broadcast": 0,
    },

    120109:{
        "No.": 120109,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100010,
        "broadcast": 0,
    },

    120110:{
        "No.": 120110,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100011,
        "broadcast": 0,
    },

    120111:{
        "No.": 120111,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100012,
        "broadcast": 0,
    },

    120112:{
        "No.": 120112,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100013,
        "broadcast": 0,
    },

    120113:{
        "No.": 120113,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100014,
        "broadcast": 0,
    },

    120114:{
        "No.": 120114,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100015,
        "broadcast": 0,
    },

    120115:{
        "No.": 120115,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100016,
        "broadcast": 0,
    },

    120116:{
        "No.": 120116,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100017,
        "broadcast": 0,
    },

    120117:{
        "No.": 120117,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100018,
        "broadcast": 0,
    },

    120118:{
        "No.": 120118,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100019,
        "broadcast": 0,
    },

    120119:{
        "No.": 120119,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100020,
        "broadcast": 0,
    },

    120120:{
        "No.": 120120,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100021,
        "broadcast": 0,
    },

    120121:{
        "No.": 120121,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100022,
        "broadcast": 0,
    },

    120122:{
        "No.": 120122,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100023,
        "broadcast": 0,
    },

    120123:{
        "No.": 120123,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100024,
        "broadcast": 0,
    },

    120124:{
        "No.": 120124,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100025,
        "broadcast": 0,
    },

    120125:{
        "No.": 120125,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100026,
        "broadcast": 0,
    },

    120126:{
        "No.": 120126,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100027,
        "broadcast": 0,
    },

    120127:{
        "No.": 120127,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100028,
        "broadcast": 0,
    },

    120128:{
        "No.": 120128,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100029,
        "broadcast": 0,
    },

    120129:{
        "No.": 120129,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100030,
        "broadcast": 0,
    },

    120130:{
        "No.": 120130,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100031,
        "broadcast": 0,
    },

    120131:{
        "No.": 120131,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100032,
        "broadcast": 0,
    },

    120132:{
        "No.": 120132,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100033,
        "broadcast": 0,
    },

    120133:{
        "No.": 120133,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100034,
        "broadcast": 0,
    },

    120134:{
        "No.": 120134,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100035,
        "broadcast": 0,
    },

    120135:{
        "No.": 120135,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100036,
        "broadcast": 0,
    },

    120136:{
        "No.": 120136,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100037,
        "broadcast": 0,
    },

    120137:{
        "No.": 120137,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100038,
        "broadcast": 0,
    },

    120138:{
        "No.": 120138,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100039,
        "broadcast": 0,
    },

    120139:{
        "No.": 120139,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100040,
        "broadcast": 0,
    },

    120140:{
        "No.": 120140,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100041,
        "broadcast": 0,
    },

    120141:{
        "No.": 120141,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100042,
        "broadcast": 0,
    },

    120142:{
        "No.": 120142,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100043,
        "broadcast": 0,
    },

    120143:{
        "No.": 120143,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100044,
        "broadcast": 0,
    },

    120144:{
        "No.": 120144,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100045,
        "broadcast": 0,
    },

    120145:{
        "No.": 120145,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100046,
        "broadcast": 0,
    },

    120146:{
        "No.": 120146,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100047,
        "broadcast": 0,
    },

    120147:{
        "No.": 120147,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100048,
        "broadcast": 0,
    },

    120148:{
        "No.": 120148,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100049,
        "broadcast": 0,
    },

    120149:{
        "No.": 120149,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100050,
        "broadcast": 0,
    },

    120150:{
        "No.": 120150,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100051,
        "broadcast": 0,
    },

    120151:{
        "No.": 120151,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100052,
        "broadcast": 0,
    },

    120152:{
        "No.": 120152,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100053,
        "broadcast": 0,
    },

    120153:{
        "No.": 120153,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100054,
        "broadcast": 0,
    },

    120154:{
        "No.": 120154,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100055,
        "broadcast": 0,
    },

    120155:{
        "No.": 120155,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100056,
        "broadcast": 0,
    },

    120156:{
        "No.": 120156,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100057,
        "broadcast": 0,
    },

    120157:{
        "No.": 120157,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100058,
        "broadcast": 0,
    },

    120158:{
        "No.": 120158,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100059,
        "broadcast": 0,
    },

    120159:{
        "No.": 120159,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100060,
        "broadcast": 0,
    },

    120160:{
        "No.": 120160,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100061,
        "broadcast": 0,
    },

    120161:{
        "No.": 120161,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100062,
        "broadcast": 0,
    },

    120162:{
        "No.": 120162,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100063,
        "broadcast": 0,
    },

    120163:{
        "No.": 120163,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100064,
        "broadcast": 0,
    },

    120164:{
        "No.": 120164,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100065,
        "broadcast": 0,
    },

    120165:{
        "No.": 120165,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100066,
        "broadcast": 0,
    },

    120166:{
        "No.": 120166,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100067,
        "broadcast": 0,
    },

    120167:{
        "No.": 120167,
        "type": 4,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 100068,
        "broadcast": 0,
    },

    120200:{
        "No.": 120200,
        "type": 8,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 100,
        "items": 0,
        "buy_price": 20,
        "effect_value": 0,
        "spirit_exp": 5,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120201:{
        "No.": 120201,
        "type": 8,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 200,
        "items": 0,
        "buy_price": 25,
        "effect_value": 0,
        "spirit_exp": 5,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120202:{
        "No.": 120202,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 300,
        "items": 0,
        "buy_price": 30,
        "effect_value": 0,
        "spirit_exp": 6,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120203:{
        "No.": 120203,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 400,
        "items": 0,
        "buy_price": 35,
        "effect_value": 0,
        "spirit_exp": 6,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120204:{
        "No.": 120204,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 500,
        "items": 0,
        "buy_price": 40,
        "effect_value": 0,
        "spirit_exp": 7,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120205:{
        "No.": 120205,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 600,
        "items": 0,
        "buy_price": 45,
        "effect_value": 0,
        "spirit_exp": 7,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120206:{
        "No.": 120206,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 700,
        "items": 0,
        "buy_price": 50,
        "effect_value": 0,
        "spirit_exp": 8,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120207:{
        "No.": 120207,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 800,
        "items": 0,
        "buy_price": 55,
        "effect_value": 0,
        "spirit_exp": 8,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120208:{
        "No.": 120208,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 900,
        "items": 0,
        "buy_price": 60,
        "effect_value": 0,
        "spirit_exp": 9,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120209:{
        "No.": 120209,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 65,
        "effect_value": 0,
        "spirit_exp": 9,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120210:{
        "No.": 120210,
        "type": 8,
        "quality": 5,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1100,
        "items": 0,
        "buy_price": 70,
        "effect_value": 0,
        "spirit_exp": 10,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120220:{
        "No.": 120220,
        "type": 8,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 100,
        "items": 0,
        "buy_price": 20,
        "effect_value": 0,
        "spirit_exp": 5,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120221:{
        "No.": 120221,
        "type": 8,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 200,
        "items": 0,
        "buy_price": 25,
        "effect_value": 0,
        "spirit_exp": 5,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120222:{
        "No.": 120222,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 300,
        "items": 0,
        "buy_price": 30,
        "effect_value": 0,
        "spirit_exp": 6,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120223:{
        "No.": 120223,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 400,
        "items": 0,
        "buy_price": 35,
        "effect_value": 0,
        "spirit_exp": 6,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120224:{
        "No.": 120224,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 500,
        "items": 0,
        "buy_price": 40,
        "effect_value": 0,
        "spirit_exp": 7,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120225:{
        "No.": 120225,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 600,
        "items": 0,
        "buy_price": 45,
        "effect_value": 0,
        "spirit_exp": 7,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120226:{
        "No.": 120226,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 700,
        "items": 0,
        "buy_price": 50,
        "effect_value": 0,
        "spirit_exp": 8,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120227:{
        "No.": 120227,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 800,
        "items": 0,
        "buy_price": 55,
        "effect_value": 0,
        "spirit_exp": 8,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120228:{
        "No.": 120228,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 900,
        "items": 0,
        "buy_price": 60,
        "effect_value": 0,
        "spirit_exp": 9,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120229:{
        "No.": 120229,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 65,
        "effect_value": 0,
        "spirit_exp": 9,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120230:{
        "No.": 120230,
        "type": 8,
        "quality": 5,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1100,
        "items": 0,
        "buy_price": 70,
        "effect_value": 0,
        "spirit_exp": 10,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120240:{
        "No.": 120240,
        "type": 8,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 100,
        "items": 0,
        "buy_price": 20,
        "effect_value": 0,
        "spirit_exp": 5,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120241:{
        "No.": 120241,
        "type": 8,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 200,
        "items": 0,
        "buy_price": 25,
        "effect_value": 0,
        "spirit_exp": 5,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120242:{
        "No.": 120242,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 300,
        "items": 0,
        "buy_price": 30,
        "effect_value": 0,
        "spirit_exp": 6,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120243:{
        "No.": 120243,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 400,
        "items": 0,
        "buy_price": 35,
        "effect_value": 0,
        "spirit_exp": 6,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120244:{
        "No.": 120244,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 500,
        "items": 0,
        "buy_price": 40,
        "effect_value": 0,
        "spirit_exp": 7,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120245:{
        "No.": 120245,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 600,
        "items": 0,
        "buy_price": 45,
        "effect_value": 0,
        "spirit_exp": 7,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120246:{
        "No.": 120246,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 700,
        "items": 0,
        "buy_price": 50,
        "effect_value": 0,
        "spirit_exp": 8,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120247:{
        "No.": 120247,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 800,
        "items": 0,
        "buy_price": 55,
        "effect_value": 0,
        "spirit_exp": 8,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120248:{
        "No.": 120248,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 900,
        "items": 0,
        "buy_price": 60,
        "effect_value": 0,
        "spirit_exp": 9,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120249:{
        "No.": 120249,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 65,
        "effect_value": 0,
        "spirit_exp": 9,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120250:{
        "No.": 120250,
        "type": 8,
        "quality": 5,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1100,
        "items": 0,
        "buy_price": 70,
        "effect_value": 0,
        "spirit_exp": 10,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120300:{
        "No.": 120300,
        "type": 8,
        "quality": 0,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 100,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 5,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120301:{
        "No.": 120301,
        "type": 8,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 200,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 6,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120302:{
        "No.": 120302,
        "type": 8,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 300,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 7,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120303:{
        "No.": 120303,
        "type": 8,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 400,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 8,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120304:{
        "No.": 120304,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 500,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 9,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120305:{
        "No.": 120305,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 600,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 10,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120306:{
        "No.": 120306,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 700,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 11,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120307:{
        "No.": 120307,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 800,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 12,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120308:{
        "No.": 120308,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 900,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 13,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120309:{
        "No.": 120309,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 14,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120310:{
        "No.": 120310,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1100,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 15,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120311:{
        "No.": 120311,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1200,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 16,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120312:{
        "No.": 120312,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1300,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 17,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120313:{
        "No.": 120313,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1400,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 18,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120314:{
        "No.": 120314,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1500,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 19,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120315:{
        "No.": 120315,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1600,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120316:{
        "No.": 120316,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1700,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 21,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120317:{
        "No.": 120317,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1800,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 22,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120318:{
        "No.": 120318,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1900,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 23,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120319:{
        "No.": 120319,
        "type": 8,
        "quality": 4,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 2000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 24,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120330:{
        "No.": 120330,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 2000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 5,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120331:{
        "No.": 120331,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120400:{
        "No.": 120400,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120401:{
        "No.": 120401,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120402:{
        "No.": 120402,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120403:{
        "No.": 120403,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120404:{
        "No.": 120404,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120405:{
        "No.": 120405,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120406:{
        "No.": 120406,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120407:{
        "No.": 120407,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120408:{
        "No.": 120408,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120409:{
        "No.": 120409,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120410:{
        "No.": 120410,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120411:{
        "No.": 120411,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120412:{
        "No.": 120412,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120413:{
        "No.": 120413,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120414:{
        "No.": 120414,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120415:{
        "No.": 120415,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120416:{
        "No.": 120416,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120417:{
        "No.": 120417,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120418:{
        "No.": 120418,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120419:{
        "No.": 120419,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120420:{
        "No.": 120420,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120421:{
        "No.": 120421,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120422:{
        "No.": 120422,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120423:{
        "No.": 120423,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 1,
    },

    120500:{
        "No.": 120500,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120501:{
        "No.": 120501,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120502:{
        "No.": 120502,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120503:{
        "No.": 120503,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120504:{
        "No.": 120504,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120505:{
        "No.": 120505,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120506:{
        "No.": 120506,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120507:{
        "No.": 120507,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120508:{
        "No.": 120508,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120509:{
        "No.": 120509,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120510:{
        "No.": 120510,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120511:{
        "No.": 120511,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120520:{
        "No.": 120520,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120521:{
        "No.": 120521,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120522:{
        "No.": 120522,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120523:{
        "No.": 120523,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120524:{
        "No.": 120524,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120525:{
        "No.": 120525,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120526:{
        "No.": 120526,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120527:{
        "No.": 120527,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120528:{
        "No.": 120528,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120529:{
        "No.": 120529,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120530:{
        "No.": 120530,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120531:{
        "No.": 120531,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120600:{
        "No.": 120600,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120601:{
        "No.": 120601,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120602:{
        "No.": 120602,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120603:{
        "No.": 120603,
        "type": 8,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 10,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120604:{
        "No.": 120604,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120605:{
        "No.": 120605,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120606:{
        "No.": 120606,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120607:{
        "No.": 120607,
        "type": 8,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 20,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120610:{
        "No.": 120610,
        "type": 9,
        "quality": 4,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120611:{
        "No.": 120611,
        "type": 9,
        "quality": 3,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120612:{
        "No.": 120612,
        "type": 9,
        "quality": 2,
        "need_level": 0,
        "can_sale": 0,
        "sale_price": 0,
        "items": 0,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120700:{
        "No.": 120700,
        "type": 5,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 60,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120701:{
        "No.": 120701,
        "type": 5,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 2000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 20,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120702:{
        "No.": 120702,
        "type": 5,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 5,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120703:{
        "No.": 120703,
        "type": 5,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 60,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120704:{
        "No.": 120704,
        "type": 5,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 2000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 20,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120705:{
        "No.": 120705,
        "type": 5,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 5,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120706:{
        "No.": 120706,
        "type": 5,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 60,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120707:{
        "No.": 120707,
        "type": 5,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 2000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 20,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120708:{
        "No.": 120708,
        "type": 5,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 5,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120709:{
        "No.": 120709,
        "type": 5,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 60,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120710:{
        "No.": 120710,
        "type": 5,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 2000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 20,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120711:{
        "No.": 120711,
        "type": 5,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 5,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120712:{
        "No.": 120712,
        "type": 5,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 60,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120713:{
        "No.": 120713,
        "type": 5,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 2000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 20,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120714:{
        "No.": 120714,
        "type": 5,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 5,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120715:{
        "No.": 120715,
        "type": 5,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 60,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120716:{
        "No.": 120716,
        "type": 5,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 2000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 20,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120717:{
        "No.": 120717,
        "type": 5,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 5,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120718:{
        "No.": 120718,
        "type": 5,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 60,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120719:{
        "No.": 120719,
        "type": 5,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 2000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 20,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120720:{
        "No.": 120720,
        "type": 5,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 5,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120721:{
        "No.": 120721,
        "type": 5,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 60,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120722:{
        "No.": 120722,
        "type": 5,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 2000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 20,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120723:{
        "No.": 120723,
        "type": 5,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 5,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120724:{
        "No.": 120724,
        "type": 5,
        "quality": 3,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 5000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 60,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120725:{
        "No.": 120725,
        "type": 5,
        "quality": 2,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 2000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 20,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120726:{
        "No.": 120726,
        "type": 5,
        "quality": 1,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1000,
        "items": 0,
        "buy_price": 0,
        "effect_value": 5,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120994:{
        "No.": 120994,
        "type": 6,
        "quality": 5,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1,
        "items": 200994,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120995:{
        "No.": 120995,
        "type": 6,
        "quality": 5,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1,
        "items": 200995,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120996:{
        "No.": 120996,
        "type": 6,
        "quality": 5,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1,
        "items": 200996,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120997:{
        "No.": 120997,
        "type": 6,
        "quality": 5,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1,
        "items": 200997,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120998:{
        "No.": 120998,
        "type": 6,
        "quality": 5,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1,
        "items": 200998,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

    120999:{
        "No.": 120999,
        "type": 6,
        "quality": 5,
        "need_level": 0,
        "can_sale": 1,
        "sale_price": 1,
        "items": 200999,
        "buy_price": 0,
        "effect_value": 0,
        "spirit_exp": 0,
        "stack_limit": 9999,
        "chip_hero_id": 0,
        "broadcast": 0,
    },

}
