#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Date :
# @Author : Jiank
# @doc
#     !!! 前方配置高能, 均为自动生成, 随意改动可能会有不可思议的事情发生 !!!
# @end
# @copyright (C) 2015, kimech

user_buy_refresh_cfg = {
    1:{
        "buy_energy": 50,
        "buy_gold": 10,
        "refresh_mission": 30,
        "arena_add_times": 10,
        "arena_refresh": 0,
        "trial_openbox_diamond": 0,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 10,
    },
    2:{
        "buy_energy": 50,
        "buy_gold": 10,
        "refresh_mission": 100,
        "arena_add_times": 10,
        "arena_refresh": 0,
        "trial_openbox_diamond": 10,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 10,
    },
    3:{
        "buy_energy": 100,
        "buy_gold": 15,
        "refresh_mission": 200,
        "arena_add_times": 15,
        "arena_refresh": 1,
        "trial_openbox_diamond": 20,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 20,
    },
    4:{
        "buy_energy": 100,
        "buy_gold": 15,
        "refresh_mission": 500,
        "arena_add_times": 15,
        "arena_refresh": 1,
        "trial_openbox_diamond": 20,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 20,
    },
    5:{
        "buy_energy": 200,
        "buy_gold": 20,
        "refresh_mission": 1000,
        "arena_add_times": 20,
        "arena_refresh": 1,
        "trial_openbox_diamond": 20,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 30,
    },
    6:{
        "buy_energy": 200,
        "buy_gold": 20,
        "refresh_mission": 2000,
        "arena_add_times": 20,
        "arena_refresh": 2,
        "trial_openbox_diamond": 40,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 30,
    },
    7:{
        "buy_energy": 300,
        "buy_gold": 25,
        "refresh_mission": 3000,
        "arena_add_times": 25,
        "arena_refresh": 2,
        "trial_openbox_diamond": 40,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 40,
    },
    8:{
        "buy_energy": 300,
        "buy_gold": 25,
        "refresh_mission": 4000,
        "arena_add_times": 25,
        "arena_refresh": 2,
        "trial_openbox_diamond": 40,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 40,
    },
    9:{
        "buy_energy": 400,
        "buy_gold": 30,
        "refresh_mission": 5000,
        "arena_add_times": 30,
        "arena_refresh": 2,
        "trial_openbox_diamond": 40,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    10:{
        "buy_energy": 400,
        "buy_gold": 30,
        "refresh_mission": 6000,
        "arena_add_times": 30,
        "arena_refresh": 5,
        "trial_openbox_diamond": 80,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    11:{
        "buy_energy": 600,
        "buy_gold": 35,
        "refresh_mission": 7000,
        "arena_add_times": 40,
        "arena_refresh": 5,
        "trial_openbox_diamond": 80,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    12:{
        "buy_energy": 600,
        "buy_gold": 35,
        "refresh_mission": 8000,
        "arena_add_times": 40,
        "arena_refresh": 5,
        "trial_openbox_diamond": 100,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    13:{
        "buy_energy": 800,
        "buy_gold": 40,
        "refresh_mission": 9000,
        "arena_add_times": 50,
        "arena_refresh": 5,
        "trial_openbox_diamond": 100,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    14:{
        "buy_energy": 800,
        "buy_gold": 40,
        "refresh_mission": 10000,
        "arena_add_times": 50,
        "arena_refresh": 10,
        "trial_openbox_diamond": 100,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    15:{
        "buy_energy": 1000,
        "buy_gold": 45,
        "refresh_mission": 11000,
        "arena_add_times": 70,
        "arena_refresh": 10,
        "trial_openbox_diamond": 100,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    16:{
        "buy_energy": 1000,
        "buy_gold": 45,
        "refresh_mission": 12000,
        "arena_add_times": 70,
        "arena_refresh": 10,
        "trial_openbox_diamond": 200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    17:{
        "buy_energy": 1200,
        "buy_gold": 50,
        "refresh_mission": 13000,
        "arena_add_times": 100,
        "arena_refresh": 10,
        "trial_openbox_diamond": 200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    18:{
        "buy_energy": 1200,
        "buy_gold": 50,
        "refresh_mission": 14000,
        "arena_add_times": 100,
        "arena_refresh": 20,
        "trial_openbox_diamond": 200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    19:{
        "buy_energy": 1400,
        "buy_gold": 55,
        "refresh_mission": 15000,
        "arena_add_times": 150,
        "arena_refresh": 20,
        "trial_openbox_diamond": 200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    20:{
        "buy_energy": 1400,
        "buy_gold": 55,
        "refresh_mission": 16000,
        "arena_add_times": 150,
        "arena_refresh": 20,
        "trial_openbox_diamond": 400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    21:{
        "buy_energy": 1600,
        "buy_gold": 60,
        "refresh_mission": 17000,
        "arena_add_times": 200,
        "arena_refresh": 20,
        "trial_openbox_diamond": 400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    22:{
        "buy_energy": 1600,
        "buy_gold": 60,
        "refresh_mission": 18000,
        "arena_add_times": 200,
        "arena_refresh": 20,
        "trial_openbox_diamond": 400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    23:{
        "buy_energy": 1800,
        "buy_gold": 65,
        "refresh_mission": 19000,
        "arena_add_times": 250,
        "arena_refresh": 20,
        "trial_openbox_diamond": 400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    24:{
        "buy_energy": 1800,
        "buy_gold": 65,
        "refresh_mission": 20000,
        "arena_add_times": 250,
        "arena_refresh": 20,
        "trial_openbox_diamond": 600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    25:{
        "buy_energy": 2000,
        "buy_gold": 70,
        "refresh_mission": 21000,
        "arena_add_times": 300,
        "arena_refresh": 20,
        "trial_openbox_diamond": 600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    26:{
        "buy_energy": 2000,
        "buy_gold": 70,
        "refresh_mission": 22000,
        "arena_add_times": 300,
        "arena_refresh": 20,
        "trial_openbox_diamond": 600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    27:{
        "buy_energy": 2200,
        "buy_gold": 75,
        "refresh_mission": 23000,
        "arena_add_times": 350,
        "arena_refresh": 20,
        "trial_openbox_diamond": 600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    28:{
        "buy_energy": 2200,
        "buy_gold": 75,
        "refresh_mission": 24000,
        "arena_add_times": 350,
        "arena_refresh": 20,
        "trial_openbox_diamond": 800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    29:{
        "buy_energy": 2400,
        "buy_gold": 80,
        "refresh_mission": 25000,
        "arena_add_times": 400,
        "arena_refresh": 20,
        "trial_openbox_diamond": 800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    30:{
        "buy_energy": 2400,
        "buy_gold": 80,
        "refresh_mission": 26000,
        "arena_add_times": 400,
        "arena_refresh": 20,
        "trial_openbox_diamond": 800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    31:{
        "buy_energy": 2600,
        "buy_gold": 85,
        "refresh_mission": 27000,
        "arena_add_times": 450,
        "arena_refresh": 20,
        "trial_openbox_diamond": 800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    32:{
        "buy_energy": 2600,
        "buy_gold": 85,
        "refresh_mission": 28000,
        "arena_add_times": 450,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    33:{
        "buy_energy": 2800,
        "buy_gold": 90,
        "refresh_mission": 29000,
        "arena_add_times": 500,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    34:{
        "buy_energy": 2800,
        "buy_gold": 90,
        "refresh_mission": 30000,
        "arena_add_times": 500,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    35:{
        "buy_energy": 3000,
        "buy_gold": 95,
        "refresh_mission": 31000,
        "arena_add_times": 550,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    36:{
        "buy_energy": 3000,
        "buy_gold": 95,
        "refresh_mission": 32000,
        "arena_add_times": 550,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    37:{
        "buy_energy": 3200,
        "buy_gold": 100,
        "refresh_mission": 33000,
        "arena_add_times": 600,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    38:{
        "buy_energy": 3200,
        "buy_gold": 100,
        "refresh_mission": 34000,
        "arena_add_times": 600,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    39:{
        "buy_energy": 3400,
        "buy_gold": 105,
        "refresh_mission": 35000,
        "arena_add_times": 650,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    40:{
        "buy_energy": 3400,
        "buy_gold": 105,
        "refresh_mission": 36000,
        "arena_add_times": 650,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    41:{
        "buy_energy": 3600,
        "buy_gold": 110,
        "refresh_mission": 37000,
        "arena_add_times": 700,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    42:{
        "buy_energy": 3600,
        "buy_gold": 110,
        "refresh_mission": 38000,
        "arena_add_times": 700,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    43:{
        "buy_energy": 3800,
        "buy_gold": 115,
        "refresh_mission": 39000,
        "arena_add_times": 750,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    44:{
        "buy_energy": 3800,
        "buy_gold": 115,
        "refresh_mission": 40000,
        "arena_add_times": 750,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    45:{
        "buy_energy": 4000,
        "buy_gold": 120,
        "refresh_mission": 41000,
        "arena_add_times": 800,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    46:{
        "buy_energy": 4000,
        "buy_gold": 120,
        "refresh_mission": 42000,
        "arena_add_times": 800,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    47:{
        "buy_energy": 4200,
        "buy_gold": 125,
        "refresh_mission": 43000,
        "arena_add_times": 850,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    48:{
        "buy_energy": 4200,
        "buy_gold": 125,
        "refresh_mission": 44000,
        "arena_add_times": 850,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    49:{
        "buy_energy": 4400,
        "buy_gold": 130,
        "refresh_mission": 45000,
        "arena_add_times": 900,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    50:{
        "buy_energy": 4400,
        "buy_gold": 130,
        "refresh_mission": 46000,
        "arena_add_times": 900,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    51:{
        "buy_energy": 4600,
        "buy_gold": 135,
        "refresh_mission": 47000,
        "arena_add_times": 950,
        "arena_refresh": 20,
        "trial_openbox_diamond": 1800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    52:{
        "buy_energy": 4600,
        "buy_gold": 135,
        "refresh_mission": 48000,
        "arena_add_times": 950,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    53:{
        "buy_energy": 4800,
        "buy_gold": 140,
        "refresh_mission": 49000,
        "arena_add_times": 1000,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    54:{
        "buy_energy": 4800,
        "buy_gold": 140,
        "refresh_mission": 50000,
        "arena_add_times": 1000,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    55:{
        "buy_energy": 5000,
        "buy_gold": 145,
        "refresh_mission": 51000,
        "arena_add_times": 1050,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    56:{
        "buy_energy": 5000,
        "buy_gold": 145,
        "refresh_mission": 52000,
        "arena_add_times": 1050,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    57:{
        "buy_energy": 5200,
        "buy_gold": 150,
        "refresh_mission": 53000,
        "arena_add_times": 1100,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    58:{
        "buy_energy": 5200,
        "buy_gold": 150,
        "refresh_mission": 54000,
        "arena_add_times": 1100,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    59:{
        "buy_energy": 5400,
        "buy_gold": 155,
        "refresh_mission": 55000,
        "arena_add_times": 1150,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    60:{
        "buy_energy": 5400,
        "buy_gold": 155,
        "refresh_mission": 56000,
        "arena_add_times": 1150,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    61:{
        "buy_energy": 5600,
        "buy_gold": 160,
        "refresh_mission": 57000,
        "arena_add_times": 1200,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    62:{
        "buy_energy": 5600,
        "buy_gold": 160,
        "refresh_mission": 58000,
        "arena_add_times": 1200,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    63:{
        "buy_energy": 5800,
        "buy_gold": 165,
        "refresh_mission": 59000,
        "arena_add_times": 1250,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    64:{
        "buy_energy": 5800,
        "buy_gold": 165,
        "refresh_mission": 60000,
        "arena_add_times": 1250,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    65:{
        "buy_energy": 6000,
        "buy_gold": 170,
        "refresh_mission": 61000,
        "arena_add_times": 1300,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    66:{
        "buy_energy": 6000,
        "buy_gold": 170,
        "refresh_mission": 62000,
        "arena_add_times": 1300,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    67:{
        "buy_energy": 6200,
        "buy_gold": 175,
        "refresh_mission": 63000,
        "arena_add_times": 1350,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    68:{
        "buy_energy": 6200,
        "buy_gold": 175,
        "refresh_mission": 64000,
        "arena_add_times": 1350,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    69:{
        "buy_energy": 6400,
        "buy_gold": 180,
        "refresh_mission": 65000,
        "arena_add_times": 1400,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    70:{
        "buy_energy": 6400,
        "buy_gold": 180,
        "refresh_mission": 66000,
        "arena_add_times": 1400,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    71:{
        "buy_energy": 6600,
        "buy_gold": 185,
        "refresh_mission": 67000,
        "arena_add_times": 1450,
        "arena_refresh": 20,
        "trial_openbox_diamond": 2800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    72:{
        "buy_energy": 6600,
        "buy_gold": 185,
        "refresh_mission": 68000,
        "arena_add_times": 1450,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    73:{
        "buy_energy": 6800,
        "buy_gold": 190,
        "refresh_mission": 69000,
        "arena_add_times": 1500,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    74:{
        "buy_energy": 6800,
        "buy_gold": 190,
        "refresh_mission": 70000,
        "arena_add_times": 1500,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    75:{
        "buy_energy": 7000,
        "buy_gold": 195,
        "refresh_mission": 71000,
        "arena_add_times": 1550,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    76:{
        "buy_energy": 7000,
        "buy_gold": 195,
        "refresh_mission": 72000,
        "arena_add_times": 1550,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    77:{
        "buy_energy": 7200,
        "buy_gold": 200,
        "refresh_mission": 73000,
        "arena_add_times": 1600,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    78:{
        "buy_energy": 7200,
        "buy_gold": 200,
        "refresh_mission": 74000,
        "arena_add_times": 1600,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    79:{
        "buy_energy": 7400,
        "buy_gold": 205,
        "refresh_mission": 75000,
        "arena_add_times": 1650,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    80:{
        "buy_energy": 7400,
        "buy_gold": 205,
        "refresh_mission": 76000,
        "arena_add_times": 1650,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    81:{
        "buy_energy": 7600,
        "buy_gold": 210,
        "refresh_mission": 77000,
        "arena_add_times": 1700,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    82:{
        "buy_energy": 7600,
        "buy_gold": 210,
        "refresh_mission": 78000,
        "arena_add_times": 1700,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    83:{
        "buy_energy": 7800,
        "buy_gold": 215,
        "refresh_mission": 79000,
        "arena_add_times": 1750,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    84:{
        "buy_energy": 7800,
        "buy_gold": 215,
        "refresh_mission": 80000,
        "arena_add_times": 1750,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    85:{
        "buy_energy": 8000,
        "buy_gold": 220,
        "refresh_mission": 81000,
        "arena_add_times": 1800,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    86:{
        "buy_energy": 8000,
        "buy_gold": 220,
        "refresh_mission": 82000,
        "arena_add_times": 1800,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    87:{
        "buy_energy": 8200,
        "buy_gold": 225,
        "refresh_mission": 83000,
        "arena_add_times": 1850,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    88:{
        "buy_energy": 8200,
        "buy_gold": 225,
        "refresh_mission": 84000,
        "arena_add_times": 1850,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    89:{
        "buy_energy": 8400,
        "buy_gold": 230,
        "refresh_mission": 85000,
        "arena_add_times": 1900,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    90:{
        "buy_energy": 8400,
        "buy_gold": 230,
        "refresh_mission": 86000,
        "arena_add_times": 1900,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    91:{
        "buy_energy": 8600,
        "buy_gold": 235,
        "refresh_mission": 87000,
        "arena_add_times": 1950,
        "arena_refresh": 20,
        "trial_openbox_diamond": 3800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    92:{
        "buy_energy": 8600,
        "buy_gold": 235,
        "refresh_mission": 88000,
        "arena_add_times": 1950,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    93:{
        "buy_energy": 8800,
        "buy_gold": 240,
        "refresh_mission": 89000,
        "arena_add_times": 2000,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    94:{
        "buy_energy": 8800,
        "buy_gold": 240,
        "refresh_mission": 90000,
        "arena_add_times": 2000,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    95:{
        "buy_energy": 9000,
        "buy_gold": 245,
        "refresh_mission": 91000,
        "arena_add_times": 2050,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    96:{
        "buy_energy": 9000,
        "buy_gold": 245,
        "refresh_mission": 92000,
        "arena_add_times": 2050,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    97:{
        "buy_energy": 9200,
        "buy_gold": 250,
        "refresh_mission": 93000,
        "arena_add_times": 2100,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    98:{
        "buy_energy": 9200,
        "buy_gold": 250,
        "refresh_mission": 94000,
        "arena_add_times": 2100,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    99:{
        "buy_energy": 9400,
        "buy_gold": 255,
        "refresh_mission": 95000,
        "arena_add_times": 2150,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    100:{
        "buy_energy": 9400,
        "buy_gold": 255,
        "refresh_mission": 96000,
        "arena_add_times": 2150,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    101:{
        "buy_energy": 9600,
        "buy_gold": 260,
        "refresh_mission": 97000,
        "arena_add_times": 2200,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    102:{
        "buy_energy": 9600,
        "buy_gold": 260,
        "refresh_mission": 98000,
        "arena_add_times": 2200,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    103:{
        "buy_energy": 9800,
        "buy_gold": 265,
        "refresh_mission": 99000,
        "arena_add_times": 2250,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    104:{
        "buy_energy": 9800,
        "buy_gold": 265,
        "refresh_mission": 100000,
        "arena_add_times": 2250,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    105:{
        "buy_energy": 10000,
        "buy_gold": 270,
        "refresh_mission": 101000,
        "arena_add_times": 2300,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    106:{
        "buy_energy": 10000,
        "buy_gold": 270,
        "refresh_mission": 102000,
        "arena_add_times": 2300,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    107:{
        "buy_energy": 10200,
        "buy_gold": 275,
        "refresh_mission": 103000,
        "arena_add_times": 2350,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    108:{
        "buy_energy": 10200,
        "buy_gold": 275,
        "refresh_mission": 104000,
        "arena_add_times": 2350,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    109:{
        "buy_energy": 10400,
        "buy_gold": 280,
        "refresh_mission": 105000,
        "arena_add_times": 2400,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    110:{
        "buy_energy": 10400,
        "buy_gold": 280,
        "refresh_mission": 106000,
        "arena_add_times": 2400,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    111:{
        "buy_energy": 10600,
        "buy_gold": 285,
        "refresh_mission": 107000,
        "arena_add_times": 2450,
        "arena_refresh": 20,
        "trial_openbox_diamond": 4800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    112:{
        "buy_energy": 10600,
        "buy_gold": 285,
        "refresh_mission": 108000,
        "arena_add_times": 2450,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    113:{
        "buy_energy": 10800,
        "buy_gold": 290,
        "refresh_mission": 109000,
        "arena_add_times": 2500,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    114:{
        "buy_energy": 10800,
        "buy_gold": 290,
        "refresh_mission": 110000,
        "arena_add_times": 2500,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    115:{
        "buy_energy": 11000,
        "buy_gold": 295,
        "refresh_mission": 111000,
        "arena_add_times": 2550,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    116:{
        "buy_energy": 11000,
        "buy_gold": 295,
        "refresh_mission": 112000,
        "arena_add_times": 2550,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    117:{
        "buy_energy": 11200,
        "buy_gold": 300,
        "refresh_mission": 113000,
        "arena_add_times": 2600,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    118:{
        "buy_energy": 11200,
        "buy_gold": 300,
        "refresh_mission": 114000,
        "arena_add_times": 2600,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    119:{
        "buy_energy": 11400,
        "buy_gold": 305,
        "refresh_mission": 115000,
        "arena_add_times": 2650,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    120:{
        "buy_energy": 11400,
        "buy_gold": 305,
        "refresh_mission": 116000,
        "arena_add_times": 2650,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    121:{
        "buy_energy": 11600,
        "buy_gold": 310,
        "refresh_mission": 117000,
        "arena_add_times": 2700,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    122:{
        "buy_energy": 11600,
        "buy_gold": 310,
        "refresh_mission": 118000,
        "arena_add_times": 2700,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    123:{
        "buy_energy": 11800,
        "buy_gold": 315,
        "refresh_mission": 119000,
        "arena_add_times": 2750,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    124:{
        "buy_energy": 11800,
        "buy_gold": 315,
        "refresh_mission": 120000,
        "arena_add_times": 2750,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    125:{
        "buy_energy": 12000,
        "buy_gold": 320,
        "refresh_mission": 121000,
        "arena_add_times": 2800,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    126:{
        "buy_energy": 12000,
        "buy_gold": 320,
        "refresh_mission": 122000,
        "arena_add_times": 2800,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    127:{
        "buy_energy": 12200,
        "buy_gold": 325,
        "refresh_mission": 123000,
        "arena_add_times": 2850,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    128:{
        "buy_energy": 12200,
        "buy_gold": 325,
        "refresh_mission": 124000,
        "arena_add_times": 2850,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    129:{
        "buy_energy": 12400,
        "buy_gold": 330,
        "refresh_mission": 125000,
        "arena_add_times": 2900,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    130:{
        "buy_energy": 12400,
        "buy_gold": 330,
        "refresh_mission": 126000,
        "arena_add_times": 2900,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    131:{
        "buy_energy": 12600,
        "buy_gold": 335,
        "refresh_mission": 127000,
        "arena_add_times": 2950,
        "arena_refresh": 20,
        "trial_openbox_diamond": 5800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    132:{
        "buy_energy": 12600,
        "buy_gold": 335,
        "refresh_mission": 128000,
        "arena_add_times": 2950,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    133:{
        "buy_energy": 12800,
        "buy_gold": 340,
        "refresh_mission": 129000,
        "arena_add_times": 3000,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    134:{
        "buy_energy": 12800,
        "buy_gold": 340,
        "refresh_mission": 130000,
        "arena_add_times": 3000,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    135:{
        "buy_energy": 13000,
        "buy_gold": 345,
        "refresh_mission": 131000,
        "arena_add_times": 3050,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    136:{
        "buy_energy": 13000,
        "buy_gold": 345,
        "refresh_mission": 132000,
        "arena_add_times": 3050,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    137:{
        "buy_energy": 13200,
        "buy_gold": 350,
        "refresh_mission": 133000,
        "arena_add_times": 3100,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    138:{
        "buy_energy": 13200,
        "buy_gold": 350,
        "refresh_mission": 134000,
        "arena_add_times": 3100,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    139:{
        "buy_energy": 13400,
        "buy_gold": 355,
        "refresh_mission": 135000,
        "arena_add_times": 3150,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    140:{
        "buy_energy": 13400,
        "buy_gold": 355,
        "refresh_mission": 136000,
        "arena_add_times": 3150,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    141:{
        "buy_energy": 13600,
        "buy_gold": 360,
        "refresh_mission": 137000,
        "arena_add_times": 3200,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    142:{
        "buy_energy": 13600,
        "buy_gold": 360,
        "refresh_mission": 138000,
        "arena_add_times": 3200,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    143:{
        "buy_energy": 13800,
        "buy_gold": 365,
        "refresh_mission": 139000,
        "arena_add_times": 3250,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    144:{
        "buy_energy": 13800,
        "buy_gold": 365,
        "refresh_mission": 140000,
        "arena_add_times": 3250,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    145:{
        "buy_energy": 14000,
        "buy_gold": 370,
        "refresh_mission": 141000,
        "arena_add_times": 3300,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    146:{
        "buy_energy": 14000,
        "buy_gold": 370,
        "refresh_mission": 142000,
        "arena_add_times": 3300,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    147:{
        "buy_energy": 14200,
        "buy_gold": 375,
        "refresh_mission": 143000,
        "arena_add_times": 3350,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6600,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    148:{
        "buy_energy": 14200,
        "buy_gold": 375,
        "refresh_mission": 144000,
        "arena_add_times": 3350,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    149:{
        "buy_energy": 14400,
        "buy_gold": 380,
        "refresh_mission": 145000,
        "arena_add_times": 3400,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    150:{
        "buy_energy": 14400,
        "buy_gold": 380,
        "refresh_mission": 146000,
        "arena_add_times": 3400,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    151:{
        "buy_energy": 14600,
        "buy_gold": 385,
        "refresh_mission": 147000,
        "arena_add_times": 3450,
        "arena_refresh": 20,
        "trial_openbox_diamond": 6800,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    152:{
        "buy_energy": 14600,
        "buy_gold": 385,
        "refresh_mission": 148000,
        "arena_add_times": 3450,
        "arena_refresh": 20,
        "trial_openbox_diamond": 7000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    153:{
        "buy_energy": 14800,
        "buy_gold": 390,
        "refresh_mission": 149000,
        "arena_add_times": 3500,
        "arena_refresh": 20,
        "trial_openbox_diamond": 7000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    154:{
        "buy_energy": 14800,
        "buy_gold": 390,
        "refresh_mission": 150000,
        "arena_add_times": 3500,
        "arena_refresh": 20,
        "trial_openbox_diamond": 7000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    155:{
        "buy_energy": 15000,
        "buy_gold": 395,
        "refresh_mission": 151000,
        "arena_add_times": 3550,
        "arena_refresh": 20,
        "trial_openbox_diamond": 7000,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    156:{
        "buy_energy": 15000,
        "buy_gold": 395,
        "refresh_mission": 152000,
        "arena_add_times": 3550,
        "arena_refresh": 20,
        "trial_openbox_diamond": 7200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    157:{
        "buy_energy": 15200,
        "buy_gold": 400,
        "refresh_mission": 153000,
        "arena_add_times": 3600,
        "arena_refresh": 20,
        "trial_openbox_diamond": 7200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    158:{
        "buy_energy": 15200,
        "buy_gold": 400,
        "refresh_mission": 154000,
        "arena_add_times": 3600,
        "arena_refresh": 20,
        "trial_openbox_diamond": 7200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    159:{
        "buy_energy": 15400,
        "buy_gold": 405,
        "refresh_mission": 155000,
        "arena_add_times": 3650,
        "arena_refresh": 20,
        "trial_openbox_diamond": 7200,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },
    160:{
        "buy_energy": 15400,
        "buy_gold": 405,
        "refresh_mission": 156000,
        "arena_add_times": 3650,
        "arena_refresh": 20,
        "trial_openbox_diamond": 7400,
        "skill_point_diamond": 50,
        "group_game_tiger_refresh": 50,
    },

}
