#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Date :
# @Author : Jiank
# @doc
#     !!! 前方配置高能, 均为自动生成, 随意改动可能会有不可思议的事情发生 !!!
# @end
# @copyright (C) 2015, kimech

vip_priv_cfg = {
    0:{
        "exp": 0,
        "buy_energy_times": 2,
        "buy_gold_times": 4,
        "reset_mission_times": 1,
        "arena_fight_cd": 600,
        "skill_point_cd": 120,
        "skip_trial_battle": 0,
        "open_ten_hangup": 0,
        "skip_arena_battle": 0,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.0,
        "group_advance_donate": 0,
        "priv_gift": {},
        "priv_gift_price": 0,
    },
    1:{
        "exp": 60,
        "buy_energy_times": 3,
        "buy_gold_times": 5,
        "reset_mission_times": 1,
        "arena_fight_cd": 600,
        "skill_point_cd": 120,
        "skip_trial_battle": 0,
        "open_ten_hangup": 0,
        "skip_arena_battle": 0,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.0,
        "group_advance_donate": 0,
        "priv_gift": {120001: 50, 3: 100, 100004: 3, 1: 100000},
        "priv_gift_price": 0,
    },
    2:{
        "exp": 300,
        "buy_energy_times": 4,
        "buy_gold_times": 7,
        "reset_mission_times": 2,
        "arena_fight_cd": 600,
        "skill_point_cd": 120,
        "skip_trial_battle": 0,
        "open_ten_hangup": 0,
        "skip_arena_battle": 0,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.0,
        "group_advance_donate": 0,
        "priv_gift": {120001: 50, 120330: 10, 14: 3, 1: 100000},
        "priv_gift_price": 180,
    },
    3:{
        "exp": 600,
        "buy_energy_times": 5,
        "buy_gold_times": 9,
        "reset_mission_times": 2,
        "arena_fight_cd": 600,
        "skill_point_cd": 60,
        "skip_trial_battle": 1,
        "open_ten_hangup": 0,
        "skip_arena_battle": 0,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.0,
        "group_advance_donate": 0,
        "priv_gift": {1: 100000, 120002: 30, 120331: 2},
        "priv_gift_price": 280,
    },
    4:{
        "exp": 1000,
        "buy_energy_times": 6,
        "buy_gold_times": 12,
        "reset_mission_times": 2,
        "arena_fight_cd": 600,
        "skill_point_cd": 60,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 0,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.0,
        "group_advance_donate": 0,
        "priv_gift": {1: 100000, 120002: 30, 120524: 1},
        "priv_gift_price": 480,
    },
    5:{
        "exp": 2000,
        "buy_energy_times": 7,
        "buy_gold_times": 16,
        "reset_mission_times": 3,
        "arena_fight_cd": 600,
        "skill_point_cd": 60,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 1,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.0,
        "group_advance_donate": 1,
        "priv_gift": {1: 100000, 120002: 30, 120103: 50},
        "priv_gift_price": 680,
    },
    6:{
        "exp": 3000,
        "buy_energy_times": 8,
        "buy_gold_times": 20,
        "reset_mission_times": 3,
        "arena_fight_cd": 600,
        "skill_point_cd": 60,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 1,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.0,
        "group_advance_donate": 1,
        "priv_gift": {1: 100000, 120002: 30, 120502: 1},
        "priv_gift_price": 880,
    },
    7:{
        "exp": 5000,
        "buy_energy_times": 9,
        "buy_gold_times": 25,
        "reset_mission_times": 3,
        "arena_fight_cd": 600,
        "skill_point_cd": 60,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 1,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.1,
        "group_advance_donate": 1,
        "priv_gift": {1: 100000, 120002: 30, 120103: 100},
        "priv_gift_price": 1280,
    },
    8:{
        "exp": 7000,
        "buy_energy_times": 10,
        "buy_gold_times": 30,
        "reset_mission_times": 3,
        "arena_fight_cd": 600,
        "skill_point_cd": 60,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 1,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.1,
        "group_advance_donate": 1,
        "priv_gift": {1: 150000, 120522: 1, 120003: 20},
        "priv_gift_price": 1680,
    },
    9:{
        "exp": 10000,
        "buy_energy_times": 11,
        "buy_gold_times": 35,
        "reset_mission_times": 3,
        "arena_fight_cd": 600,
        "skill_point_cd": 5,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 1,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.1,
        "group_advance_donate": 1,
        "priv_gift": {1: 150000, 120067: 20, 120103: 160},
        "priv_gift_price": 2280,
    },
    10:{
        "exp": 15000,
        "buy_energy_times": 12,
        "buy_gold_times": 40,
        "reset_mission_times": 4,
        "arena_fight_cd": 600,
        "skill_point_cd": 5,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 1,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.1,
        "group_advance_donate": 1,
        "priv_gift": {1: 150000, 120410: 1, 120067: 20},
        "priv_gift_price": 2680,
    },
    11:{
        "exp": 20000,
        "buy_energy_times": 13,
        "buy_gold_times": 50,
        "reset_mission_times": 4,
        "arena_fight_cd": 600,
        "skill_point_cd": 5,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 1,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.1,
        "group_advance_donate": 1,
        "priv_gift": {1: 200000, 2: 8888, 120067: 40},
        "priv_gift_price": 3380,
    },
    12:{
        "exp": 30000,
        "buy_energy_times": 14,
        "buy_gold_times": 60,
        "reset_mission_times": 4,
        "arena_fight_cd": 600,
        "skill_point_cd": 5,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 1,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.15,
        "group_advance_donate": 1,
        "priv_gift": {1: 200000, 120067: 60, 120100: 150},
        "priv_gift_price": 4880,
    },
    13:{
        "exp": 60000,
        "buy_energy_times": 15,
        "buy_gold_times": 80,
        "reset_mission_times": 5,
        "arena_fight_cd": 60,
        "skill_point_cd": 5,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 1,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.15,
        "group_advance_donate": 1,
        "priv_gift": {120520: 1, 1: 200000, 120067: 100, 120500: 1},
        "priv_gift_price": 6880,
    },
    14:{
        "exp": 120000,
        "buy_energy_times": 16,
        "buy_gold_times": 100,
        "reset_mission_times": 5,
        "arena_fight_cd": 60,
        "skill_point_cd": 5,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 1,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.2,
        "group_advance_donate": 1,
        "priv_gift": {1: 300000, 120067: 200, 120100: 150},
        "priv_gift_price": 10880,
    },
    15:{
        "exp": 200000,
        "buy_energy_times": 17,
        "buy_gold_times": 160,
        "reset_mission_times": 5,
        "arena_fight_cd": 60,
        "skill_point_cd": 5,
        "skip_trial_battle": 1,
        "open_ten_hangup": 1,
        "skip_arena_battle": 1,
        "daily_spec_chip": 1,
        "daily_world_chat_times": 9999,
        "group_auto_sign": 1,
        "arena_add_times": 160,
        "arena_refresh_times": 100,
        "trial_score_percent": 0.3,
        "group_advance_donate": 1,
        "priv_gift": {120400: 1, 1: 400000, 120067: 300},
        "priv_gift_price": 20880,
    },

}

vip_exp_level_cfg = {}

for level, priv in vip_priv_cfg.iteritems():
    vip_exp_level_cfg[priv["exp"]] = level

